-- Script pour vérifier les colonnes existantes dans les tables SILOG
-- Base: SEDI_ERP

USE [SEDI_ERP];
GO

PRINT '=== Vérification des colonnes dans RESSOURC ===';
SELECT 
    COLUMN_NAME,
    DATA_TYPE,
    CHARACTER_MAXIMUM_LENGTH,
    IS_NULLABLE
FROM INFORMATION_SCHEMA.COLUMNS
WHERE TABLE_SCHEMA = 'dbo'
  AND TABLE_NAME = 'RESSOURC'
  AND (
    COLUMN_NAME LIKE '%Statut%' OR
    COLUMN_NAME LIKE '%STATUT%' OR
    COLUMN_NAME LIKE '%DateConsultation%' OR
    COLUMN_NAME LIKE '%DATE_CONSULTATION%' OR
    COLUMN_NAME LIKE '%Date_Consultation%' OR
    COLUMN_NAME LIKE '%Consultation%' OR
    COLUMN_NAME LIKE '%CONSULTATION%'
  )
ORDER BY COLUMN_NAME;
GO

PRINT '';
PRINT '=== Vérification des colonnes dans LCTC ===';
SELECT 
    COLUMN_NAME,
    DATA_TYPE,
    CHARACTER_MAXIMUM_LENGTH,
    IS_NULLABLE
FROM INFORMATION_SCHEMA.COLUMNS
WHERE TABLE_SCHEMA = 'dbo'
  AND TABLE_NAME = 'LCTC'
  AND (
    COLUMN_NAME LIKE '%DateConsultation%' OR
    COLUMN_NAME LIKE '%DATE_CONSULTATION%' OR
    COLUMN_NAME LIKE '%Date_Consultation%' OR
    COLUMN_NAME LIKE '%Consultation%' OR
    COLUMN_NAME LIKE '%CONSULTATION%'
  )
ORDER BY COLUMN_NAME;
GO

PRINT '';
PRINT '=== Vérification des colonnes dans LCTE ===';
SELECT 
    COLUMN_NAME,
    DATA_TYPE,
    CHARACTER_MAXIMUM_LENGTH,
    IS_NULLABLE
FROM INFORMATION_SCHEMA.COLUMNS
WHERE TABLE_SCHEMA = 'dbo'
  AND TABLE_NAME = 'LCTE'
  AND (
    COLUMN_NAME LIKE '%DateConsultation%' OR
    COLUMN_NAME LIKE '%DATE_CONSULTATION%' OR
    COLUMN_NAME LIKE '%Date_Consultation%' OR
    COLUMN_NAME LIKE '%Consultation%' OR
    COLUMN_NAME LIKE '%CONSULTATION%'
  )
ORDER BY COLUMN_NAME;
GO

PRINT '';
PRINT '=== Toutes les colonnes de RESSOURC (pour référence) ===';
SELECT TOP 20
    COLUMN_NAME,
    DATA_TYPE,
    CHARACTER_MAXIMUM_LENGTH
FROM INFORMATION_SCHEMA.COLUMNS
WHERE TABLE_SCHEMA = 'dbo'
  AND TABLE_NAME = 'RESSOURC'
ORDER BY ORDINAL_POSITION;
GO
