locals {
  hosts_normalized = {
    for key, h in var.hosts : key => {
      hostname     = h.hostname
      address      = h.address
      os           = h.os
      role         = h.role
      enabled      = coalesce(h.enabled, true)
      ssh_user     = coalesce(h.ssh_user, var.ssh_user_default)
      ssh_key_path = coalesce(h.ssh_key_path, var.ssh_private_key_path_default)
    }
  }

  hosts_enabled = {
    for key, h in local.hosts_normalized : key => h
    if h.enabled
  }

  linux_enabled = {
    for key, h in local.hosts_enabled : key => h
    if h.os == "linux"
  }

  silog_enabled = {
    for key, h in local.hosts_enabled : key => h
    if h.os == "windows" && h.role == "silog"
  }

  ansible_inventory_path = "${path.module}/../ansible/inventories/generated/fsop.yml"

  ansible_inventory_yaml = <<-YAML
# GENERATED by Terraform - do not edit by hand.
# Source: terraform/ + terraform.tfvars -> terraform apply
# See terraform/README.md and ansible/README.md

all:
  children:
%{if length(local.linux_enabled) > 0~}
    fsop_linux:
      children:
%{for key, h in local.linux_enabled~}
        fsop_${h.role}:
          hosts:
            ${h.hostname}:
              ansible_host: ${h.address}
              ansible_user: ${h.ssh_user}
              ansible_ssh_private_key_file: ${h.ssh_key_path}
              fsop_role: ${h.role}
%{endfor~}
%{endif~}
%{if length(local.silog_enabled) > 0~}
    silog_runners:
      hosts:
%{for key, h in local.silog_enabled~}
        ${h.hostname}:
          ansible_host: ${h.address}
          ansible_user: ${h.ssh_user}
          ansible_ssh_private_key_file: ${h.ssh_key_path}
          ansible_connection: "{{ lookup('env', 'SILOG_ANSIBLE_CONNECTION') | default('ssh', true) }}"
          ansible_password: "{{ lookup('env', 'SILOG_ANSIBLE_PASSWORD') | default('', true) }}"
          ansible_port: "{{ lookup('env', 'SILOG_ANSIBLE_PORT') | default(omit) }}"
          ansible_winrm_transport: ntlm
          ansible_winrm_server_cert_validation: ignore
          ansible_shell_type: powershell
          fsop_role: silog
%{endfor~}
%{endif~}
YAML
}

resource "local_file" "ansible_inventory" {
  filename        = local.ansible_inventory_path
  file_permission = "0644"
  content         = local.ansible_inventory_yaml
}
